# -*- mode: ruby -*-
# vi: set ft=ruby :

# Choose OS version
BOX_IMAGE = "ubuntu/jammy64"
BOX_VERSION = "20240207.0.0"

# CPU and memory and disk settings
CPU = 2
MEMORY = 2048
DISK_SIZE = "100GB"

# VMs prefix
CP_HOSTNAME = "c1-cp"
NODE_HOSTNAME = "c1-node"

# Number of Control Plane and Nodes to create
NUMBER_OF_CP = 1
NUMBER_OF_NODES = 3

# IP CIDR of the newtork. Network will be bridged
IP_RANGE = "192.168.1."

Vagrant.configure("2") do |config|

  # Populate /etc/hosts with the IP address of all control plane and node intances
  # CP will start with 192.168.1.10 and nodes will start at 192.168.1.20
  config.vm.provision "shell", env: { "IP_RANGE" => IP_RANGE, "NUMBER_OF_CP" => NUMBER_OF_CP, "NUMBER_OF_NODES" => NUMBER_OF_NODES}, inline: <<-SHELL
    for i in `seq ${NUMBER_OF_CP}`; do
      echo "$IP_RANGE$(($i + 10 -1)) #{CP_HOSTNAME}$i" >> /etc/hosts
    done
    for j in `seq ${NUMBER_OF_NODES}`; do
      echo "$IP_RANGE$(($j + 20 -1)) #{NODE_HOSTNAME}$j" >> /etc/hosts
    done
  SHELL

  # Create the Instances that will have the control plain installed
  (1..NUMBER_OF_CP).each do |i|
      config.vm.define "#{CP_HOSTNAME}#{i}" do |cp|
          cp.vm.box = BOX_IMAGE
          cp.vm.box_version = BOX_VERSION

          cp.vm.disk :disk, size: DISK_SIZE, primary: true

          cp.vm.provider "virtualbox" do |vbcp|
              vbcp.name = "#{CP_HOSTNAME}#{i}"
              vbcp.cpus = CPU
              vbcp.memory = MEMORY
          end

          cp.vm.network "public_network", ip: IP_RANGE+"#{i + 10 -1}"
          cp.vm.hostname = "#{CP_HOSTNAME}#{i}"

      end
  end

  # Create the Instances that will play the node roles
  (1..NUMBER_OF_NODES).each do |i|
      config.vm.define "#{NODE_HOSTNAME}#{i}" do |node|
          node.vm.box = BOX_IMAGE
          node.vm.box_version = BOX_VERSION

          node.vm.disk :disk, size: DISK_SIZE, primary: true

          node.vm.provider "virtualbox" do |vbnode|
              vbnode.name = "#{NODE_HOSTNAME}#{i}"
              vbnode.cpus = CPU
              vbnode.memory = MEMORY
          end

          node.vm.network "public_network", ip: IP_RANGE+"#{i + 20 -1}"
          node.vm.hostname = "#{NODE_HOSTNAME}#{i}"

      end
  end

end
