# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/jammy64"
BOX_VERSION = "20240207.0.0"
CPU = 2
MEMORY = 2048

CP_HOSTNAME = "c1-cp"
NODE_HOSTNAME = "c1-node"

NUMBER_OF_CP = 1
NUMBER_OF_NODES = 3

IP_RANGE = "192.168.1."

Vagrant.configure("2") do |config|

  config.vm.provision "shell", env: { "IP_RANGE" => IP_RANGE, "NUMBER_OF_CP" => NUMBER_OF_CP, "NUMBER_OF_NODES" => NUMBER_OF_NODES}, inline: <<-SHELL
    for i in `seq ${NUMBER_OF_CP}`; do
      echo "$IP_RANGE$(($i + 10 -1)) #{CP_HOSTNAME}$i" >> /etc/hosts
    done
    for j in `seq ${NUMBER_OF_NODES}`; do
      echo "$IP_RANGE$(($j + 20 -1)) #{NODE_HOSTNAME}$j" >> /etc/hosts
    done
  SHELL

  (1..NUMBER_OF_CP).each do |i|
      config.vm.define "#{CP_HOSTNAME}#{i}" do |cp|
          cp.vm.box = BOX_IMAGE
          cp.vm.box_version = BOX_VERSION

          cp.vm.provider "virtualbox" do |vbcp|
              vbcp.name = "#{CP_HOSTNAME}#{i}"
              vbcp.cpus = CPU
              vbcp.memory = MEMORY
          end

          cp.vm.network "public_network", ip: IP_RANGE+"#{i + 10 -1}"
          cp.vm.hostname = "#{CP_HOSTNAME}#{i}"

      end
  end

  (1..NUMBER_OF_NODES).each do |i|
      config.vm.define "#{NODE_HOSTNAME}#{i}" do |node|
          node.vm.box = BOX_IMAGE
          node.vm.box_version = BOX_VERSION

          node.vm.provider "virtualbox" do |vbnode|
              vbnode.name = "#{NODE_HOSTNAME}#{i}"
              vbnode.cpus = CPU
              vbnode.memory = MEMORY
          end

          node.vm.network "public_network", ip: IP_RANGE+"#{i + 20 -1}"
          node.vm.hostname = "#{NODE_HOSTNAME}#{i}"

      end
  end

end
